enum PracticeCategory {
  straightness,
  potting,
  technique,
  position,
  gameplay,
}

enum PracticeDifficulty {
  beginner,
  intermediate,
  advanced,
}

class PracticeDrill {
  const PracticeDrill({
    required this.id,
    required this.title,
    required this.category,
    required this.goal,
    required this.description,
    required this.recommendedReps,
    required this.difficulty,
    required this.focus,
    required this.imageAsset,
  });

  final String id;
  final String title;
  final PracticeCategory category;
  final String goal;
  final String description;
  final int recommendedReps;
  final PracticeDifficulty difficulty;
  final String focus;
  final String imageAsset;
}

class DrillProgress {
  const DrillProgress({
    required this.attempts,
    required this.successes,
    required this.bestPercent,
    required this.lastPercent,
  });

  final int attempts;
  final int successes;
  final double bestPercent;
  final double lastPercent;

  DrillProgress copyWith({
    int? attempts,
    int? successes,
    double? bestPercent,
    double? lastPercent,
  }) {
    return DrillProgress(
      attempts: attempts ?? this.attempts,
      successes: successes ?? this.successes,
      bestPercent: bestPercent ?? this.bestPercent,
      lastPercent: lastPercent ?? this.lastPercent,
    );
  }

  Map<String, dynamic> toJson() => {
        'attempts': attempts,
        'successes': successes,
        'bestPercent': bestPercent,
        'lastPercent': lastPercent,
      };

  factory DrillProgress.fromJson(Map<String, dynamic> json) {
    return DrillProgress(
      attempts: (json['attempts'] as num?)?.toInt() ?? 0,
      successes: (json['successes'] as num?)?.toInt() ?? 0,
      bestPercent: (json['bestPercent'] as num?)?.toDouble() ?? 0,
      lastPercent: (json['lastPercent'] as num?)?.toDouble() ?? 0,
    );
  }

  static const empty = DrillProgress(
    attempts: 0,
    successes: 0,
    bestPercent: 0,
    lastPercent: 0,
  );
}

const List<PracticeDrill> kPracticeDrills = [
  PracticeDrill(
    id: 'reimering_g_1',
    title: 'Übung 1 Geradlinigkeit',
    category: PracticeCategory.straightness,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Folie wird exakt mittig von Kopf- zur Fußbande aufgelegt Die weiße Kugel (WK) wird einen Diamanten unterhalb des Kopfpunkts aufgebaut Das Queue wird bei dieser Übung auf der Bande abgelegt Der Stoß soll einhändig mit einer natürlichen Unterarmbewegung ausgeführt werden Der Führungsarm wird auf dem linken bzw. rechten Oberschenkel abgelegt WK soll auf der roten Linie über die Fußbande an die Kopfbande zurückgespielt werden WK darf die Trainingsfolie dabei nicht verlassen Jeder erfolgreiche Versuch bringt 1 Punkt 20 Wiederholungen pro Durchgang - es können maximal 20 Punkte erreicht werden',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_g_1.png',
  ),
  PracticeDrill(
    id: 'reimering_g_2',
    title: 'Übung 2 Geradlinigkeit',
    category: PracticeCategory.straightness,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Folie wird exakt mittig von Kopf- zur Fußbande aufgelegt Die weiße Kugel (WK) wird auf dem Kopfpunkt aufgebaut Der Stoß soll mit einer natürlichen Unterarmbewegung ausgeführt werden WK soll auf der roten Linie über die Fußbande an die Kopfbande zurückgespielt werden WK darf die Trainingsfolie dabei nicht verlassen Jeder erfolgreiche Versuch bringt 1 Punkt 20 Wiederholungen pro Durchgang - es können maximal 20 Punkte erreicht werden',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_g_2.png',
  ),
  PracticeDrill(
    id: 'reimering_g_3',
    title: 'Übung 3 Geradlinigkeit',
    category: PracticeCategory.straightness,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Folie wird exakt mittig von Kopf- zur Fußbande aufgelegt Die weiße Kugel (WK) wird auf dem Kopfpunkt aufgebaut Der Objektball (OB) wird einen Diamanten davor aufgebaut Der Stoß soll mit einer natürlichen Unterarmbewegung als Stoppball ausgeführt werden OB soll auf der roten Linie über die Fußbande zurück auf die WK gespielt werden WK darf die Trainingsfolie vor dem zweiten Kontakt nicht verlassen Jeder erfolgreiche Versuch bringt 1 Punkt 20 Wiederholungen pro Durchgang - es können maximal 20 Punkte erreicht werden',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_g_3.png',
  ),
  PracticeDrill(
    id: 'reimering_g_5',
    title: 'Übung 5 Geradlinigkeit/Stoppball',
    category: PracticeCategory.straightness,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Folie wird exakt auf der Mittellinie aufgelegt, sodass die Markierung der weißen Kugel (WK) genau auf dem halben Diamanten liegt Die WK wird auf der passenden Markierung aufgebaut Der OB wird auf der Objektballmarkierung aufgebaut OB soll als Stoppball in die Mitteltasche gespielt werden Die WK soll exakt auf der Geisterballmarkierung liegen bleiben Jeder erfolgreiche Versuch bringt 1 Punkt 20 Wiederholungen pro Durchgang - es können maximal 20 Punkte erreicht werden',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_g_5.png',
  ),
  PracticeDrill(
    id: 'reimering_g_6',
    title: 'Übung 6 Geradlinigkeit/Rückläufer',
    category: PracticeCategory.straightness,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Folie wird exakt auf der Mittellinie aufgelegt, sodass die Markierung der weißen Kugel (WK) genau auf dem halben Diamanten liegt Die WK wird auf der passenden Markierung aufgebaut Der OB wird auf der Objektballmarkierung aufgebaut OB soll als Rückläufer in die Mitteltasche gespielt werden, sodass die WK soll Mitteltasche zurückläuft Jeder erfolgreiche Versuch bringt 1 Punkt 20 Wiederholungen pro Durchgang - es können maximal 20 Punkte erreicht werden',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_g_6.png',
  ),
  PracticeDrill(
    id: 'reimering_g_7',
    title: 'Übung 7 Geradlinigkeit/Nachläufer',
    category: PracticeCategory.straightness,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Folie wird exakt auf der Mittellinie aufgelegt, sodass die Markierung der weißen Kugel (WK) genau auf dem halben Diamanten liegt Die WK wird auf der passenden Markierung aufgebaut Der OB wird auf der Objektballmarkierung aufgebaut OB soll als Nachläufer in die Mitteltasche gespielt werden, sodass die WK in die Mitteltasche nachläuft Jeder erfolgreiche Versuch bringt 1 Punkt 20 Wiederholungen pro Durchgang - es können maximal 20 Punkte erreicht werden',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_g_7.png',
  ),
  PracticeDrill(
    id: 'reimering_g_e1',
    title: 'Übung 2 Geradlinigkeit/Stoppball',
    category: PracticeCategory.straightness,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Folie wird exakt von Tasche zu Tasche aufgelegt, sodass die zweite Markierung auf der Kopflinie aufliegt Die weiße Kugel (WK) wird auf der Kopflinie aufgebaut Der Objektball (OB) wird einen Diamanten davor aufgebaut OB soll als Stoppball in die gegenüberliegende Ecktasche gespielt werden, sodass die WK exakt am Treffpunkt des OB zum stehen kommt Jeder erfolgreiche Versuch bringt 1 Punkt 20 Wiederholungen pro Durchgang (10 Fußrechts/10 Fußlinks) - es können maximal 20 Punkte erreicht werden',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_g_e1.png',
  ),
  PracticeDrill(
    id: 'reimering_g_s1',
    title: 'Übung 3.1 Kurz Geradlinigkeit/Stoppball',
    category: PracticeCategory.straightness,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die weiße Kugel (WK) wird auf der Kopflinie aufgebaut Der Objektball (OB) wird in einer Linie einen Diamanten davor aufgebaut OB soll als Stoppball in die gegenüberliegende Ecktasche gespielt werden, sodass die WK exakt am Treffpunkt des OB zum stehen kommt Jeder erfolgreiche Versuch bringt 1 Punkt 20 Wiederholungen pro Durchgang (10 Fußrechts/10 Fußlinks) - es können maximal 20 Punkte erreicht werden',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_g_s1.png',
  ),
  PracticeDrill(
    id: 'reimering_g_s2',
    title: 'Übung 3.2 Kurz Geradlinigkeit/Rückläufer',
    category: PracticeCategory.straightness,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die weiße Kugel (WK) wird auf der Kopflinie aufgebaut Der Objektball (OB) wird in einer Linie einen Diamanten davor aufgebaut OB soll als Rückläufer in die gegenüberliegende Ecktasche gespielt werden, sodass die WK in die Kopftasche zurückläuft Jeder erfolgreiche Versuch bringt 1 Punkt 20 Wiederholungen pro Durchgang (10 Fußrechts/10 Fußlinks) - es können maximal 20 Punkte erreicht werden',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_g_s2.png',
  ),
  PracticeDrill(
    id: 'reimering_g_s3',
    title: 'Übung 3.3 Kurz Geradlinigkeit/Nachläufer',
    category: PracticeCategory.straightness,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die weiße Kugel (WK) wird auf der Kopflinie aufgebaut Der Objektball (OB) wird in einer Linie einen Diamanten davor aufgebaut OB soll als Nachläufer in die gegenüberliegende Ecktasche gespielt werden, sodass die WK in die Ecktasche nachläuft Jeder erfolgreiche Versuch bringt 1 Punkt 20 Wiederholungen pro Durchgang (10 Fußrechts/10 Fußlinks) - es können maximal 20 Punkte erreicht werden',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_g_s3.png',
  ),
  PracticeDrill(
    id: 'reimering_g_m1',
    title: 'Übung 4.1 Mittel Geradlinigkeit/Stoppball',
    category: PracticeCategory.straightness,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die weiße Kugel (WK) wird auf der Kopflinie aufgebaut Der Objektball (OB) wird in einer Linie einen Diamanten davor aufgebaut OB soll als Stoppball in die gegenüberliegende Ecktasche gespielt werden, sodass die WK exakt am Treffpunkt des OB zum stehen kommt Jeder erfolgreiche Versuch bringt 1 Punkt 20 Wiederholungen pro Durchgang (10 Fußrechts/10 Fußlinks) - es können maximal 20 Punkte erreicht werden',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_g_m1.png',
  ),
  PracticeDrill(
    id: 'reimering_g_m2',
    title: 'Übung 4.2 Mittel Geradlinigkeit/Rückläufer',
    category: PracticeCategory.straightness,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die weiße Kugel (WK) wird auf der Kopflinie aufgebaut Der Objektball (OB) wird in einer Linie einen Diamanten davor aufgebaut OB soll als Rückläufer in die gegenüberliegende Ecktasche gespielt werden, sodass die WK in die Kopftasche zurückläuft Jeder erfolgreiche Versuch bringt 1 Punkt 20 Wiederholungen pro Durchgang (10 Fußrechts/10 Fußlinks) - es können maximal 20 Punkte erreicht werden',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_g_m2.png',
  ),
  PracticeDrill(
    id: 'reimering_g_m3',
    title: 'Übung 4.3 Mittel Geradlinigkeit/Nachläufer',
    category: PracticeCategory.straightness,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die weiße Kugel (WK) wird auf der Kopflinie aufgebaut Der Objektball (OB) wird in einer Linie einen Diamanten davor aufgebaut OB soll als Nachläufer in die gegenüberliegende Ecktasche gespielt werden, sodass die WK in die Ecktasche nachläuft Jeder erfolgreiche Versuch bringt 1 Punkt 20 Wiederholungen pro Durchgang (10 Fußrechts/10 Fußlinks) - es können maximal 20 Punkte erreicht werden',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_g_m3.png',
  ),
  PracticeDrill(
    id: 'reimering_s_1',
    title: 'Übung 1 Senkreferenzen',
    category: PracticeCategory.potting,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Objektballmarkierung des Pocket-Sniper wird auf dem Diamantenkreuz vor der Ecktasche unten rechts aufgesetzt Die weiße Kugel (WK) wird nacheinander auf den verbleibenden Diamantenkreuzen aufgebaut Der Objektball (OB) wird nacheinander von den verschiedenen Positionen in die Ecktasche versenkt OB wird dabei immer als natürlicher Nachläufer ohne Effet gespielt Jeder erfolgreiche Versuch bringt 1 Punkt Jeder Ball wird 3x pro Durchgang gespielt - es können maximal 60 Punkte erreicht werden',
    recommendedReps: 60,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Konstanz',
    imageAsset: 'assets/images/practice/reimering_s_1.png',
  ),
  PracticeDrill(
    id: 'reimering_s_2',
    title: 'Treffpunkt 3/4 Ball Treffpunkt 1/2 Ball Treffpunkt 1/4 Ball Übung 2 Ecktasche Links/Rechts Senkreferenzen',
    category: PracticeCategory.potting,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Objektballmarkierung des Pocket-Sniper wird auf dem Fußpunkt in Richtung Ecktasche aufgelegt Die weiße Kugel (WK) wird auf den verlängerten Referenzlinien aufgebaut Es werden der Reihe nach die Senkreferenzen 3/4 Ball, 1/2 Ball und 1/4 Ball gespielt Der Objektball (OB) wird dabei immer als natürlicher Nachläufer ohne Effet gespielt Jeder erfolgreiche Versuch bringt 1 Punkt Jeder Ball wird 5x pro Seite gespielt - es können maximal 60 Punkte erreicht werden',
    recommendedReps: 60,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_s_2.png',
  ),
  PracticeDrill(
    id: 'reimering_s_3',
    title: 'Treffpunkt 3/4 Ball Treffpunkt 1/2 Ball Treffpunkt 1/4 Ball Übung 3 Mitteltasche Rechts/Links Senkreferenzen',
    category: PracticeCategory.potting,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Objektballmarkierung des Pocket-Sniper wird auf dem Fußpunkt in Richtung Mitteltasche aufgelegt Die weiße Kugel (WK) wird auf den verlängerten Referenzlinien aufgebaut Es werden der Reihe nach die Senkreferenzen 3/4 Ball, 1/2 Ball und 1/4 Ball gespielt Der Objektball (OB) wird dabei immer als natürlicher Nachläufer ohne Effet gespielt Jeder erfolgreiche Versuch bringt 1 Punkt Jeder Ball wird 5x pro Seite gespielt - es können maximal 60 Punkte erreicht werden',
    recommendedReps: 60,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_s_3.png',
  ),
  PracticeDrill(
    id: 'reimering_s_4',
    title: 'Übung 4 Senkreferenzen',
    category: PracticeCategory.potting,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Der Objektball (OB) wird, wie in der Aufbauskizze dargestellt, mit 1 Diamant Abstand zur MItteltasche aufgebaut Die weiße Kugel (WK) wird mit einer Kugelbreite Abstand zur Bande an den Dimanten bzw. an den Tasche aufgebaut Der Objektball (OB) wird nacheinander von den verschiedenen Positionen in die Mitteltasche versenkt OB wird dabei immer als natürlicher Nachläufer ohne Effet gespielt Jeder erfolgreiche Versuch bringt 1 Punkt Jeder Ball wird 3x pro Durchgang gespielt - es können maximal 33 Punkte erreicht werden',
    recommendedReps: 33,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Konstanz',
    imageAsset: 'assets/images/practice/reimering_s_4.png',
  ),
  PracticeDrill(
    id: 'reimering_s_5_1',
    title: 'Übung 5.1 -2 Seitenwechsel Senkreferenzen',
    category: PracticeCategory.potting,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Objektbälle (OB) werden, wie in der Aufbauskizze dargestellt, mit 1 Diamant Abstand zur langen Bande aufgebaut Die weiße Kugel (WK) wird auf der Kopflinie mit 1 Diamant Abstand zur langen Bande aufgebaut Die Objektbälle (OB) werden nacheinander in die Ecktasche versenkt OB wird dabei immer als natürlicher Nachläufer ohne Effet gespielt Jeder erfolgreiche Versuch bringt 1 Punkt Jeder Ball wird 3x pro Durchgang gespielt - es können maximal 15 Punkte erreicht werden',
    recommendedReps: 15,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_s_5_1.png',
  ),
  PracticeDrill(
    id: 'reimering_s_5_3',
    title: 'Übung 5.3-4 Seitenwechsel Senkreferenzen',
    category: PracticeCategory.potting,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Objektbälle (OB) werden, wie in der Aufbauskizze dargestellt, auf der Mittelachse aufgebaut Die weiße Kugel (WK) wird auf dem Kopfpunkt aufgebaut Die Objektbälle (OB) werden nacheinander in die Ecktasche versenkt OB wird dabei immer als natürlicher Nachläufer ohne Effet gespielt Jeder erfolgreiche Versuch bringt 1 Punkt Jeder Ball wird 3x pro Durchgang gespielt - es können maximal 15 Punkte erreicht werden',
    recommendedReps: 15,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_s_5_3.png',
  ),
  PracticeDrill(
    id: 'reimering_t_1',
    title: 'Übung 1 Technikreferenz',
    category: PracticeCategory.technique,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die weiße Kugel wird mit einem Abstand von einem halben Diamanten aufgebaut Der Objektball wird auf einer Linie zur weißen Kugel aufgebaut. Der Objektball muss exakt in einer Linie zur weißen Kugel liegen Objektball wird als Stopp-, Lauf- und Rückläufer jeweils auf die Referenzkugeln gespielt Jeder erfolgreiche Versuch bringt 1 Punkt 5 Wiederholungen pro Referenzpunkt - es können maximal 15 Punkte erreicht werden',
    recommendedReps: 5,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Effet',
    imageAsset: 'assets/images/practice/reimering_t_1.png',
  ),
  PracticeDrill(
    id: 'reimering_t_2',
    title: 'Übung 2 Techniktraining',
    category: PracticeCategory.technique,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die weiße Kugel wird mit einem Abstand von einem halben Diamanten aufgebaut Der Objektball wird auf einer Linie zur weißen Kugel aufgebaut. Der Objektball muss exakt in einer Linie zur weißen Kugel liegen Objektball wird als Stopp-, Lauf- und Rückläufer auf die Referenzkugeln 1-9 gespielt Jeder erfolgreiche Versuch bringt 1 Punkt 3 Wiederholungen pro Referenzkugel - es können maximal 27 Punkte erreicht werden',
    recommendedReps: 3,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Effet',
    imageAsset: 'assets/images/practice/reimering_t_2.png',
  ),
  PracticeDrill(
    id: 'reimering_t_6',
    title: 'Übung 6 Steigerung Technikreferenz',
    category: PracticeCategory.technique,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die weiße Kugel (WK) wird auf der Kopflinie auf dem ersten Diamanten aufgebaut. Der Objektball (OB) wird eine Kugelbreite nach dem ersten Diamanten aufgebaut. Der OB muss exakt in einer Linie zur WK liegen. OB wird als Stopp-, Nach- und Rückläufer jeweils auf die Referenzkugeln gespielt. Jeder erfolgreiche Versuch bringt 1 Punkt. 5 Wiederholungen pro Referenzpunkt - es können maximal 15 Punkte erreicht werden.',
    recommendedReps: 15,
    difficulty: PracticeDifficulty.advanced,
    focus: 'Effet',
    imageAsset: 'assets/images/practice/reimering_t_6.png',
  ),
  PracticeDrill(
    id: 'reimering_t_3_1',
    title: 'Übung 3.1 Technik',
    category: PracticeCategory.technique,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Der Spielball darf auf der gestrichelten Linie frei verlegt werden Der Objektball muss bei jedem Stoß in die Mitteltasche versenkt werden Der Spielball soll entweder die Bande berühren oder zwischen den beiden Kugeln durchlaufen Jedes erfolgreiche Versuch bringt 1 Punkt Es werden 2 Durchgänge gespielt - es können maximal 32 Punkte erreicht werden',
    recommendedReps: 32,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_t_3_1.png',
  ),
  PracticeDrill(
    id: 'reimering_t_3_2',
    title: 'Übung 3.2 Technik',
    category: PracticeCategory.technique,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Der Spielball darf auf der gestrichelten Linie frei verlegt werden Der Objektball muss bei jedem Stoß in die Mitteltasche versenkt werden Der Spielball soll nacheinander die Kugeln 1-14 abtreffen Jedes erfolgreiche Versuch bringt 1 Punkt Es werden 2 Durchgänge gespielt - es können maximal 28 Punkte erreicht werden',
    recommendedReps: 28,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_t_3_2.png',
  ),
  PracticeDrill(
    id: 'reimering_t_33',
    title: 'Übung 33 Position',
    category: PracticeCategory.technique,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die weiße Kugel (WK) und der Objektball (OB) werden wie dargestellt aufgebaut Die WK kann auf der gestrichelten Linie frei verlegt werden Der OB wird als Nachläufer wahlweise mit Effet gespielt OB soll je nach Position in die linke oder rechte Mitteltasche gespielt werden und die Positionsfelder anlaufen bzw. die WK soll in den Positionsfeldern liegen bleiben Die WK muss immer über die untere kurze Bande laufen weitere Banden sind erlaubt Jeder erfolgreiche Versuch bringt 1 Punkt Jeder Ball wird 2x pro Durchgang gespielt - es können maximal 64 Punkte erreicht werden 27 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 28 29 30 31 32',
    recommendedReps: 64,
    difficulty: PracticeDifficulty.advanced,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_t_33.png',
  ),
  PracticeDrill(
    id: 'reimering_p_1',
    title: 'Übung 1 Position',
    category: PracticeCategory.position,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'In dieser Übung werden abwechselnd Reihen und Dreiecke gespielt Position in der Farbe weiß = Reihe / Position in der Farbe rot = Dreieck Zu Beginn werden die Kugeln der von 1-3 in einer Reihe aufgebaut Die weiße Kugel darf bei jeder Reihe/Dreieck frei verlegt werden Die Kugeln dürfen ohne festgelegte Reihenfolge in alle Taschen versenkt werden Wird ein Ball nicht versenkt oder eine Kugel berührt ist die Reihe/Dreieck beendet Nach der ersten Reihe wandert der niedrigste Ball in die nächste Position, wobei so von Reihe zu Dreieck usw. getauscht wird Jeder erfolgreiche Versuch bringt 1 Punkt Es werden 3 Durchgänge gespielt - es können maximal 63 Punkte erreicht werden Position 1 Position 2 Position 3 Position 4 Position 5 Position 6 Position 7',
    recommendedReps: 63,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Rhythmus',
    imageAsset: 'assets/images/practice/reimering_p_1.png',
  ),
  PracticeDrill(
    id: 'reimering_p_2',
    title: 'Übung 2 Position',
    category: PracticeCategory.position,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Zu Beginn werden die Kugeln 1-3 aufgebaut Die weiße Kugel darf bei jeder Reihe frei verlegt werden Die Kugeln dürfen ohne festgelegte Reihenfolge in alle Taschen versenkt werden Wird ein Ball nicht versenkt oder eine Kugel berührt ist die Reihe beendet Für die nächste Reihe wird die niedrigste Kugel entfernt und auf dem nächsten freien Spot neu positioniert Jeder erfolgreiche Versuch bringt 1 Punkt Es werden 3 Durchgänge gespielt - es können maximal 63 Punkte erreicht werden Reihe 1 Reihe 2 Reihe 3 Reihe 4 Reihe 5 Reihe 6 Reihe 7',
    recommendedReps: 63,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Rhythmus',
    imageAsset: 'assets/images/practice/reimering_p_2.png',
  ),
  PracticeDrill(
    id: 'reimering_p_3',
    title: 'Übung 3 Position',
    category: PracticeCategory.position,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Zu Beginn werden die Kugeln der Reihe 1 aufgebaut Die weiße Kugel darf bei jeder Reihe frei verlegt werden Die Kugeln dürfen ohne festgelegte Reihenfolge in alle Taschen versenkt werden Wird ein Ball nicht versenkt oder eine Kugel berührt ist die Reihe beendet Nacheinander werden die Reihen 1-7 gespielt, wobei immer nur die aktuelle Reihe versenkt wird Jeder erfolgreiche Versuch bringt 1 Punkt Es werden 3 Durchgänge gespielt - es können maximal 63 Punkte erreicht werden Reihe 2',
    recommendedReps: 63,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Rhythmus',
    imageAsset: 'assets/images/practice/reimering_p_3.png',
  ),
  PracticeDrill(
    id: 'reimering_p_4_5',
    title: 'Übung 45 Position',
    category: PracticeCategory.position,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Objektbälle (OB) 1-4 werden wie dargestellt aufgebaut OB dürfen müssen in nummerische Reihenfolge auf die beiden Ecktaschen gespielt werden Die Weiße Kugel darf zu Beginn der Aufnahme frei auf dem Tisch verlegt werden Wird ein Ball nicht versenkt oder eine Kugel berührt ist die Aufnahme beendet Nach erfolgreichem Versuch wandern die Kugeln zur nächsten Position 1 zur 4 / 4 zur 2 / 2 zur 3 / 3 zur 1 etc. Jumpshots und Banker sind nicht erlaubt Jeder erfolgreich versenkte Ball bringt 1 Punkt Es werden 3 Durchgänge pro Position gespielt - es können maximal 12 Punkte erreicht werden',
    recommendedReps: 12,
    difficulty: PracticeDifficulty.advanced,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_p_4_5.png',
  ),
  PracticeDrill(
    id: 'reimering_p_5_2',
    title: 'Übung 52 Position',
    category: PracticeCategory.position,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Objektbälle (OB) 1-9 werden wie dargestellt aufgebaut OB 1-9 müssen in nummerische Reihenfolge in die vorgegebenen Taschen versenkt werden Die Weiße Kugel darf frei auf dem Tisch verlegt werden Wird ein Ball nicht versenkt oder eine Kugel berührt ist die Aufnahme beendet Jumpshots, Banker und Vorbänder sind nicht erlaubt Jeder erfolgreich versenkte Ball bringt 1 Punkt Es werden 3 Durchgänge gespielt - es können maximal 27 Punkte erreicht werden',
    recommendedReps: 27,
    difficulty: PracticeDifficulty.advanced,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_p_5_2.png',
  ),
  PracticeDrill(
    id: 'reimering_p_4_4',
    title: 'Übung 44 Position',
    category: PracticeCategory.position,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Objektbälle (OB) 1-15 werden frei auf dem Tisch verteilt Ziel ist es, 3x5 Bälle (5 Bälle = 1 Pärchen) ohne nummerische Reihenfolge zu versenken Ball in Hand zu Beginn eines Pärchens Wird ein Ball nicht versenkt ist die Aufnahme beendet Jedes erfolgreich versenkte Pärchen bringt 1 Punkt Es werden 3 Durchgänge gespielt - es können maximal 9 Punkte erreicht werden',
    recommendedReps: 9,
    difficulty: PracticeDifficulty.advanced,
    focus: 'Konstanz',
    imageAsset: 'assets/images/practice/reimering_p_4_4.png',
  ),
  PracticeDrill(
    id: 'reimering_p_4_2',
    title: 'Übung 42 Position',
    category: PracticeCategory.position,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Objektbälle (OB) 1-14 werden frei auf dem Tisch verteilt Ziel ist es, 7x2 Bälle (2 Bälle = 1 Pärchen) ohne nummerische Reihenfolge zu versenken Ball in Hand zu Beginn eines Pärchens Die Übung soll nur mit Stoppbällen und Nachläufern gespielt werden Wird ein Ball nicht versenkt ist die Aufnahme beendet Jedes erfolgreich versenkte Pärchen bringt 1 Punkt Es werden 3 Durchgänge gespielt - es können maximal 21 Punkte erreicht werden',
    recommendedReps: 21,
    difficulty: PracticeDifficulty.advanced,
    focus: 'Konstanz',
    imageAsset: 'assets/images/practice/reimering_p_4_2.png',
  ),
  PracticeDrill(
    id: 'reimering_p_4_3',
    title: 'Übung 43 Position',
    category: PracticeCategory.position,
    goal: 'Übung nach Vorgabe absolvieren.',
    description: 'Die Objektbälle (OB) 1-15 werden frei auf dem Tisch verteilt Ziel ist es, 5x3 Bälle (3 Bälle = 1 Pärchen) ohne nummerische Reihenfolge zu versenken Ball in Hand zu Beginn eines Pärchens Die Übung soll nur mit Stoppbällen und Nachläufern gespielt werden Wird ein Ball nicht versenkt ist die Aufnahme beendet Jedes erfolgreich versenkte Pärchen bringt 1 Punkt Es werden 3 Durchgänge gespielt - es können maximal 15 Punkte erreicht werden',
    recommendedReps: 15,
    difficulty: PracticeDifficulty.advanced,
    focus: 'Konstanz',
    imageAsset: 'assets/images/practice/reimering_p_4_3.png',
  ),
];

const List<String> kPreShotChecklist = [
  'Zielpunkt an Bande oder Objektball fixieren.',
  'Standbein auf Stoßlinie, stabiler Stand.',
  'Queue mittig auf der Weißen, gerade Führung.',
  'Bestätigungsphase (Ja/Nein-Check) vor dem Stoß.',
  'Ruhige Rückwärtsbewegung, kein plötzliches Reißen.',
  'Nach dem Stoß ruhig stehen bleiben (Freeze).',
  'Ergebnis reflektieren: Körper, Queue, Ball.',
];
