enum PracticeCategory {
  straightness,
  potting,
  technique,
  position,
  gameplay,
}

enum PracticeDifficulty {
  beginner,
  intermediate,
  advanced,
}

class PracticeDrill {
  const PracticeDrill({
    required this.id,
    required this.title,
    required this.category,
    required this.goal,
    required this.description,
    required this.recommendedReps,
    required this.difficulty,
    required this.focus,
    required this.imageAsset,
  });

  final String id;
  final String title;
  final PracticeCategory category;
  final String goal;
  final String description;
  final int recommendedReps;
  final PracticeDifficulty difficulty;
  final String focus;
  final String imageAsset;
}

class DrillProgress {
  const DrillProgress({
    required this.attempts,
    required this.successes,
    required this.bestPercent,
    required this.lastPercent,
  });

  final int attempts;
  final int successes;
  final double bestPercent;
  final double lastPercent;

  DrillProgress copyWith({
    int? attempts,
    int? successes,
    double? bestPercent,
    double? lastPercent,
  }) {
    return DrillProgress(
      attempts: attempts ?? this.attempts,
      successes: successes ?? this.successes,
      bestPercent: bestPercent ?? this.bestPercent,
      lastPercent: lastPercent ?? this.lastPercent,
    );
  }

  Map<String, dynamic> toJson() => {
        'attempts': attempts,
        'successes': successes,
        'bestPercent': bestPercent,
        'lastPercent': lastPercent,
      };

  factory DrillProgress.fromJson(Map<String, dynamic> json) {
    return DrillProgress(
      attempts: (json['attempts'] as num?)?.toInt() ?? 0,
      successes: (json['successes'] as num?)?.toInt() ?? 0,
      bestPercent: (json['bestPercent'] as num?)?.toDouble() ?? 0,
      lastPercent: (json['lastPercent'] as num?)?.toDouble() ?? 0,
    );
  }

  static const empty = DrillProgress(
    attempts: 0,
    successes: 0,
    bestPercent: 0,
    lastPercent: 0,
  );
}

const List<PracticeDrill> kPracticeDrills = [
  PracticeDrill(
    id: 'reimering_g_1',
    title: 'Geradlinigkeit 1: Weiße auf Bande',
    category: PracticeCategory.straightness,
    goal: 'Weiße zurück auf Linie spielen (einhändig).',
    description: 'Die Weiße von der Kopfbande zur Fußbande spielen und auf der selben Linie zurückführen. Queue liegt auf der Bande auf.',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_g_1.png',
  ),
  PracticeDrill(
    id: 'reimering_g_2',
    title: 'Geradlinigkeit 2: Weiße normal',
    category: PracticeCategory.straightness,
    goal: 'Weiße zurück auf Linie spielen (normaler Stand).',
    description: 'Wie Übung 1, aber mit normalem Stand und Bockhand. Die Weiße muss auf der Linie zurückkehren.',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_g_2.png',
  ),
  PracticeDrill(
    id: 'reimering_g_3',
    title: 'Geradlinigkeit 3: Stoppball-Rücklauf',
    category: PracticeCategory.straightness,
    goal: 'Objektball treffen und Weiße zurückführen.',
    description: 'Objektball auf Linie spielen, sodass dieser zurückkommt und die Weiße trifft.',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_g_3.png',
  ),
  PracticeDrill(
    id: 'reimering_g_5',
    title: 'Geradlinigkeit 5: Stoppball Mitteltasche',
    category: PracticeCategory.straightness,
    goal: 'Präziser Stoppball in die Mitteltasche.',
    description: 'Objektball in die Mitteltasche lochen. Die Weiße muss exakt auf der Geistball-Position liegen bleiben.',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_g_5.png',
  ),
  PracticeDrill(
    id: 'reimering_g_6',
    title: 'Geradlinigkeit 6: Rückläufer Mitteltasche',
    category: PracticeCategory.straightness,
    goal: 'Kontrollierter Rückläufer in die Mitteltasche.',
    description: 'Objektball lochen, Weiße läuft zurück in die gegenüberliegende Mitteltasche.',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_g_6.png',
  ),
  PracticeDrill(
    id: 'reimering_g_7',
    title: 'Geradlinigkeit 7: Nachläufer Mitteltasche',
    category: PracticeCategory.straightness,
    goal: 'Kontrollierter Nachläufer in die Mitteltasche.',
    description: 'Objektball lochen, Weiße folgt dem Objektball in die Mitteltasche.',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_g_7.png',
  ),
  PracticeDrill(
    id: 'reimering_g_e1',
    title: 'Geradlinigkeit E1: Stoppball Ecktasche',
    category: PracticeCategory.straightness,
    goal: 'Präziser Stoppball über längere Distanz.',
    description: 'Objektball in Ecktasche lochen, Weiße stoppt am Treffpunkt.',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_g_e1.png',
  ),
  PracticeDrill(
    id: 'reimering_g_s1',
    title: 'Geradlinigkeit S1: Stoppball (Kurz)',
    category: PracticeCategory.straightness,
    goal: 'Stoppball auf kurze Distanz.',
    description: 'Kurze Distanz zur Ecktasche. Weiße stoppt exakt.',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_g_s1.png',
  ),
  PracticeDrill(
    id: 'reimering_g_s2',
    title: 'Geradlinigkeit S2: Rückläufer (Kurz)',
    category: PracticeCategory.straightness,
    goal: 'Rückläufer in Kopftasche.',
    description: 'Objektball in Ecktasche, Weiße läuft zurück in die Kopftasche.',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_g_s2.png',
  ),
  PracticeDrill(
    id: 'reimering_g_s3',
    title: 'Geradlinigkeit S3: Nachläufer (Kurz)',
    category: PracticeCategory.straightness,
    goal: 'Nachläufer in Ecktasche.',
    description: 'Objektball in Ecktasche, Weiße folgt nach.',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_g_s3.png',
  ),
  PracticeDrill(
    id: 'reimering_g_m1',
    title: 'Geradlinigkeit M1: Stoppball (Mittel)',
    category: PracticeCategory.straightness,
    goal: 'Stoppball auf mittlere Distanz.',
    description: 'Mittlere Distanz zur Ecktasche. Fokus auf sauberen Treffpunkt.',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_g_m1.png',
  ),
  PracticeDrill(
    id: 'reimering_g_m2',
    title: 'Geradlinigkeit M2: Rückläufer (Mittel)',
    category: PracticeCategory.straightness,
    goal: 'Rückläufer auf mittlere Distanz.',
    description: 'Mittlere Distanz zur Ecktasche. Weiße läuft zurück zur Kopftasche.',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_g_m2.png',
  ),
  PracticeDrill(
    id: 'reimering_g_m3',
    title: 'Geradlinigkeit M3: Nachläufer (Mittel)',
    category: PracticeCategory.straightness,
    goal: 'Nachläufer auf mittlere Distanz.',
    description: 'Mittlere Distanz zur Ecktasche. Weiße folgt in die Tasche.',
    recommendedReps: 20,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_g_m3.png',
  ),
  PracticeDrill(
    id: 'reimering_s_1',
    title: 'Senken 1: Ecktasche Referenzen',
    category: PracticeCategory.potting,
    goal: 'Sicherheit beim Lochen aus verschiedenen Winkeln.',
    description: 'Objektbälle von verschiedenen Diamantenpositionen als Nachläufer in die Ecktasche lochen.',
    recommendedReps: 60,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Konstanz',
    imageAsset: 'assets/images/practice/reimering_s_1.png',
  ),
  PracticeDrill(
    id: 'reimering_s_2',
    title: 'Senken 2: Ecktasche (3/4, 1/2, 1/4)',
    category: PracticeCategory.potting,
    goal: 'Verständnis von Treffpunkten (Winkel).',
    description: 'Lerne die Treffpunkte für 3/4, 1/2 und 1/4 Ball in die Ecktasche.',
    recommendedReps: 60,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_s_2.png',
  ),
  PracticeDrill(
    id: 'reimering_s_3',
    title: 'Senken 3: Mitteltasche (3/4, 1/2, 1/4)',
    category: PracticeCategory.potting,
    goal: 'Verständnis von Treffpunkten (Mitteltasche).',
    description: 'Lerne die Treffpunkte für 3/4, 1/2 und 1/4 Ball in die Mitteltasche.',
    recommendedReps: 60,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_s_3.png',
  ),
  PracticeDrill(
    id: 'reimering_s_4',
    title: 'Senken 4: Mitteltasche Referenzen',
    category: PracticeCategory.potting,
    goal: 'Sicherheit beim Lochen in die Mitteltasche.',
    description: 'Objektbälle aus verschiedenen Positionen als Nachläufer in die Mitteltasche lochen.',
    recommendedReps: 33,
    difficulty: PracticeDifficulty.beginner,
    focus: 'Konstanz',
    imageAsset: 'assets/images/practice/reimering_s_4.png',
  ),
  PracticeDrill(
    id: 'reimering_s_5_1',
    title: 'Senken 5.1: Seitenwechsel (1)',
    category: PracticeCategory.potting,
    goal: 'Lochen mit kurzem Nachläufer.',
    description: 'Objektbälle mit einem Diamanten Abstand zur Bande lochen.',
    recommendedReps: 15,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_s_5_1.png',
  ),
  PracticeDrill(
    id: 'reimering_s_5_3',
    title: 'Senken 5.3: Seitenwechsel (2)',
    category: PracticeCategory.potting,
    goal: 'Lochen von der Mittelachse.',
    description: 'Objektbälle von der Mittelachse in die Ecktasche lochen.',
    recommendedReps: 15,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Präzision',
    imageAsset: 'assets/images/practice/reimering_s_5_3.png',
  ),
  PracticeDrill(
    id: 'reimering_t_1',
    title: 'Technik 1: Referenzpunkte',
    category: PracticeCategory.technique,
    goal: 'Beherrschung von Stopp, Lauf und Rückläufer.',
    description: 'Auf gerader Linie Stoppball, Nachläufer und Rückläufer auf bestimmte Zielkugeln spielen.',
    recommendedReps: 15,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Effet',
    imageAsset: 'assets/images/practice/reimering_t_1.png',
  ),
  PracticeDrill(
    id: 'reimering_t_2',
    title: 'Technik 2: Training 1-9',
    category: PracticeCategory.technique,
    goal: 'Feine Dosierung des Effets.',
    description: 'Stopp, Lauf und Rückläufer auf Referenzkugeln 1-9 spielen.',
    recommendedReps: 27,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Effet',
    imageAsset: 'assets/images/practice/reimering_t_2.png',
  ),
  PracticeDrill(
    id: 'reimering_t_6',
    title: 'Technik 6: Steigerung',
    category: PracticeCategory.technique,
    goal: 'Technik auf Distanz.',
    description: 'Wie Technik 1, aber mit größerem Abstand zwischen Weißer und Objektball.',
    recommendedReps: 15,
    difficulty: PracticeDifficulty.advanced,
    focus: 'Effet',
    imageAsset: 'assets/images/practice/reimering_t_6.png',
  ),
  PracticeDrill(
    id: 'reimering_t_3_1',
    title: 'Technik 3.1: Mitteltasche (Bande)',
    category: PracticeCategory.technique,
    goal: 'Positionskontrolle über die Bande.',
    description: 'Objektball in Mitteltasche lochen, Weiße muss die Bande berühren oder zwischen Kugeln durchlaufen.',
    recommendedReps: 32,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_t_3_1.png',
  ),
  PracticeDrill(
    id: 'reimering_t_3_2',
    title: 'Technik 3.2: Kugeln abtreffen',
    category: PracticeCategory.technique,
    goal: 'Präzises Treffen von Positionszielen.',
    description: 'Objektball in Mitteltasche, Weiße muss nacheinander die Kugeln 1-14 treffen.',
    recommendedReps: 28,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_t_3_2.png',
  ),
  PracticeDrill(
    id: 'reimering_t_33',
    title: 'Technik 33: Positionsfelder',
    category: PracticeCategory.technique,
    goal: 'Genaue Positionsablage.',
    description: 'Objektball in Mitteltasche, Weiße muss in vorgegebenen Positionsfeldern liegen bleiben.',
    recommendedReps: 64,
    difficulty: PracticeDifficulty.advanced,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_t_33.png',
  ),
  PracticeDrill(
    id: 'reimering_p_1',
    title: 'Position 1: Reihen & Dreiecke',
    category: PracticeCategory.position,
    goal: 'Gefühl für den Kugelverlauf im Spiel.',
    description: 'Abwechselnd Reihen und Dreiecke spielen. Fokus auf Kugelberührungsvermeidung.',
    recommendedReps: 63,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Rhythmus',
    imageAsset: 'assets/images/practice/reimering_p_1.png',
  ),
  PracticeDrill(
    id: 'reimering_p_2',
    title: 'Position 2: Kugel-Shift',
    category: PracticeCategory.position,
    goal: 'Anpassung an neue Situationen.',
    description: 'Nach jeder Reihe die niedrigste Kugel entfernen und neu positionieren.',
    recommendedReps: 63,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Rhythmus',
    imageAsset: 'assets/images/practice/reimering_p_2.png',
  ),
  PracticeDrill(
    id: 'reimering_p_3',
    title: 'Position 3: Reihen 1-7',
    category: PracticeCategory.position,
    goal: 'Konstanz im Positionsspiel.',
    description: 'Nacheinander die Reihen 1-7 abräumen.',
    recommendedReps: 63,
    difficulty: PracticeDifficulty.intermediate,
    focus: 'Rhythmus',
    imageAsset: 'assets/images/practice/reimering_p_3.png',
  ),
  PracticeDrill(
    id: 'reimering_p_4_5',
    title: 'Position 4.5: Numerisch Ecktasche',
    category: PracticeCategory.position,
    goal: 'Strenge Positionskontrolle.',
    description: 'Kugeln in numerischer Reihenfolge in die Ecktaschen lochen.',
    recommendedReps: 12,
    difficulty: PracticeDifficulty.advanced,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_p_4_5.png',
  ),
  PracticeDrill(
    id: 'reimering_p_5_2',
    title: 'Position 5.2: Vorgegebene Taschen',
    category: PracticeCategory.position,
    goal: 'Maximale Kontrolle.',
    description: 'Numerische Reihenfolge in exakt vorgegebene Taschen.',
    recommendedReps: 27,
    difficulty: PracticeDifficulty.advanced,
    focus: 'Kontrolle',
    imageAsset: 'assets/images/practice/reimering_p_5_2.png',
  ),
  PracticeDrill(
    id: 'reimering_p_4_4',
    title: 'Position 4.4: Pärchen (3x5)',
    category: PracticeCategory.position,
    goal: 'Aufbau von kleinen Serien.',
    description: '3 Pärchen à 5 Bälle ohne numerische Reihenfolge lochen.',
    recommendedReps: 9,
    difficulty: PracticeDifficulty.advanced,
    focus: 'Konstanz',
    imageAsset: 'assets/images/practice/reimering_p_4_4.png',
  ),
  PracticeDrill(
    id: 'reimering_p_4_2',
    title: 'Position 4.2: Pärchen (7x2)',
    category: PracticeCategory.position,
    goal: 'Stopp- und Nachlauffokus.',
    description: '7 Pärchen à 2 Bälle, nur Stoppbälle und Nachläufer erlaubt.',
    recommendedReps: 21,
    difficulty: PracticeDifficulty.advanced,
    focus: 'Konstanz',
    imageAsset: 'assets/images/practice/reimering_p_4_2.png',
  ),
  PracticeDrill(
    id: 'reimering_p_4_3',
    title: 'Position 4.3: Pärchen (5x3)',
    category: PracticeCategory.position,
    goal: 'Erweitertes Pärchenspiel.',
    description: '5 Pärchen à 3 Bälle, nur Stoppbälle und Nachläufer erlaubt.',
    recommendedReps: 15,
    difficulty: PracticeDifficulty.advanced,
    focus: 'Konstanz',
    imageAsset: 'assets/images/practice/reimering_p_4_3.png',
  ),
];

const List<String> kPreShotChecklist = [
  'Zielpunkt an Bande oder Objektball fixieren.',
  'Standbein auf Stoßlinie, stabiler Stand.',
  'Queue mittig auf der Weißen, gerade Führung.',
  'Bestätigungsphase (Ja/Nein-Check) vor dem Stoß.',
  'Ruhige Rückwärtsbewegung, kein plötzliches Reißen.',
  'Nach dem Stoß ruhig stehen bleiben (Freeze).',
  'Ergebnis reflektieren: Körper, Queue, Ball.',
];
